### ISSUE TITLE
Minor Bug: Button to make a character elite is inconsistently broken

### ISSUE THREAD

**Issue by R2devo** [fafranco82/swdestinydb#115] opened 2017-04-15 00:51 UTC
Not sure why it stopped working, I had just finished making a deck, it was working fine, made a clone of another and I could not make any of the characters elite. I tried to replicate the results and  tested an older deck which worked fine along with a new blank deck, I also cloned the broken deck again and it was still broken. Not really an important bug but irritating in its apparent inexplicability.

**Comment by fafranco82** [comment] 2017-04-15 08:10
Is sounds strange... maybe it's caused by the cards included in your 'broken' deck. Can you tell me the full list of that deck to try it out in dev environment?

**Comment by fafranco82** [comment] 2017-04-15 08:31
I've just tried editing my villains deck and add all exisitng characters with maximum dice (and the same with heroes) and I've not found any troubles...

**Comment by R2devo** [comment] 2017-04-15 15:12
Here is the list http://swdestinydb.com/deck/view/188223 , I can do the same, it's just this deck and clones of it that are broken.

On Apr 15, 2017, at 4:31 AM, Francisco Franco Eslava <notifications@github.com> wrote:

I've just tried editing my villains deck and add all exisitng characters with maximum dice (and the same with heroes) and I've not found any troubles...

**Comment by fafranco82** [comment] 2017-04-16 07:51
Fixed with 2effdedb6a639bcc3e009ad12df7b483d7aebb5b! :)

Lure of Power caused this... the 'no symbol' issue made symbols chart to break... already fixed :)

**Closed by fafranco82** 2017-04-16 07:51 UTC
Labels: bug
