### ISSUE TITLE
ARH Aphra with Extra Droids

### ISSUE THREAD

**Issue by Darth-Grimm** [fafranco82/swdestinydb#346] opened 2021-02-23 15:40 UTC
I was building a deck using the new Aphra which allows you to add 6 set aside droids into your deck after setup. These droids could be any color or any faction, they just need to be from the same block the deck is being built from (i.e. ARH std). There does not seem to be an allowance for the extra droids to be added for TTS play, or am I missing something? Thanks!

**Comment by mlogie** [comment] 2021-05-14 14:17
Hello @Darth-Grimm I was just setting about trying to fix this problem, but ran into an issue. The issue is that you can set aside any number of droids up to 6, and you can choose this, ad hoc, based on your opponent. I could edit the db so you have to include 6 droids, but allowing a flexible number of extra droids, from 0 to 6, is going to be problematic for db design, and not representative of how the deck works in real life anyway (since you'll probably be taking 6-10 droids with you and choosing which ones to include based on your match-up). For that reason, I think this functionality should not be added to the db, and if you publish a deck you list your 6ish flex droids in the text desription, for adding in after seeing what your opponent is playing.

**Comment by mlogie** [comment] 2021-05-14 14:17
Based on my above @fafranco82 I think you can close this issue, if you agree.

**Comment by fafranco82** [comment] 2021-05-14 18:06
I agree with @mlogie . Closing this.

**Closed by fafranco82** 2021-05-14 18:06 UTC

**Comment by Darth-Grimm** [comment] 2021-05-15 14:25
Yes, thank you!"Jimmy the TANK, larger than life and twice as ugly!"
-------- Original message --------From: Francisco Franco Eslava ***@***.***> Date: 5/14/21  2:06 PM  (GMT-05:00) To: fafranco82/swdestinydb ***@***.***> Cc: Darth-Grimm ***@***.***>, Mention ***@***.***> Subject: Re: [fafranco82/swdestinydb] ARH Aphra with Extra Droids (#346) 
I agree with @mlogie . Closing this.
